### PR TITLE
use workspace dependencies for tower

### LINKED ISSUE #776: use workspace dependencies
It's easier to maintain and also easier to see what is used by using workspace dependencies.
For the crate itself it doesn't change much and for the user it works the same.
It's however easier ergonomics for maintainers and contributors.

I can open a PR for you if you want,
pretty easy to transition to it thanks to a tool by luke:
https://github.com/mainmatter/cargo-autoinherit

### PR DESCRIPTION
**Pull request by GlenDC**
Closes #776

### CODE REVIEW

**Comment by GlenDC** [comment]
@tobz this would require a MSRV bump to 1.64 (currently it is 1.63): https://github.com/rust-lang/cargo/blob/master/CHANGELOG.md#cargo-164-2022-09-22

**Comment by tobz** [comment]
Seems fine to bump: 1.64 is still from September 2022 so we're far far ahead of the support window goal.

**Comment by GlenDC** [comment]
> Seems fine to bump: 1.64 is still from September 2022 so we're far far ahead of the support window goal.

✅

**Comment by tobz** [comment]
Just fixed some conflicts and made some small tweaks in the process, namely using the short-form of the `dtolnay/rust-toolchain` action where you can pass the Rust toolchain version as the action version (i.e., you get the stable toolchain by using `dtolnay/rust-toolchain@stable`)

**Pull request merged**
