### PR TITLE
Middleware trait.

### PR DESCRIPTION
**Pull request by withoutboats**

### CODE REVIEW

**Comment by nayato** [comment]
@carllerche Finagle does it with a couple of things: `Filter.andThen(factory: ServiceFactory): ServiceFactory` and `LoadBalancerFactory.newEndpoint(addr: Address): ServiceFactory` which is used to compose Service Factories and not just Services.

**Comment by dmexe** [comment]
what is the current state of the middleware trait, it could able to merge?

**Comment by carllerche** [comment]
I have been experimenting with this trait here: https://github.com/carllerche/tower-web/tree/master/src/middleware. There are some differences.

I will be working to upstream `Middleware` soonish.

**Comment by carllerche** [comment]
Given the above comment, I am going to close this PR.

**Pull request closed without merging**
