### PR TITLE
layer: Implement Layer for tuples of up to 16 elements

### PR DESCRIPTION
**Pull request by jplatte**
cc @davidpdrsn @LucioFranco

### CODE REVIEW

**Comment by LucioFranco** [comment]
Seems really cool! I would love to seem some examples with it.

**Comment by jplatte** [comment]
Okay, I updated the first commit to be more consistent (I had a few `TNs` instead of `LNs`) and then added a new commit for the reversed order. Like that, it's easy to reverse-apply the second commit to change the order later, if wanted 🙂

**Comment by davidpdrsn** [comment]
Sweet! I can confirm that it matches `ServerBuilder` now.

**Comment by jplatte** [comment]
Anything that still needs to happen before this can be merged?

**Review by davidpdrsn — APPROVED** [review]
Nope I think it's good to go :)

**Pull request merged**
