### PR TITLE
fix: relax MSRV to 1.63

### LINKED ISSUE #785: Changelog says that MSRV is 1.63 but it's 1.64
Encountered in https://github.com/hyperium/hyper-util/pull/144

### PR DESCRIPTION
**Pull request by tottoto**
Resolves #785. Relaxes MSRV to 1.63 from 1.64.

### CODE REVIEW

**Comment by paolobarbolini** [comment]
Considering that the published crate gets the `Cargo.toml` flattened I wander if the MSRV is already 1.63 without this PR :thinking:. See https://docs.rs/crate/tower/0.5.1/source/Cargo.toml

**Comment by jplatte** [comment]
This effectively reverts https://github.com/tower-rs/tower/pull/778. Is there a reason you chose to do that instead of fixing #785 the "obvious" way, by updating the changelog?

**Comment by tottoto** [comment]
I'm not sure what is the obvious way, but the reason is `hyper-util`'s MSRV is 1.63 and `tower` doesn't use any 1.64 features other than workspace inheritance. As I think maintaining support for older versions of Rust also incurs a certain cost, if it does not conform to tower's policy, I will withdraw the proposal.

**Comment by tottoto** [comment]
I'm not sure what is the obvious way, but the reason is `hyper-util`'s MSRV is 1.63 and `tower` doesn't use any 1.64 features other than workspace inheritance. As I think maintaining support for older versions of Rust incurs a certain cost, if this does not conform to tower's policy, I will withdraw this proposal.

**Comment by jplatte** [comment]
I don't have a strong opinion on this one way or the other, let's see what Sean says in https://github.com/hyperium/hyper-util/pull/144.

**Comment by paolobarbolini** [comment]
Isn't the MSRV effectively 1.63 once the crate is published? I'd expect a `cargo` version not aware of workspace dependencies to still be able to parse this https://docs.rs/crate/tower/0.5.1/source/Cargo.toml

**Comment by jplatte** [comment]
That's a good point...

**Comment by seanmonstar** [comment]
At least for hyper-util, this isn't needed, since I removed the dependency on `tower`.

**Comment by tottoto** [comment]
Closed as the main motivation has been resolved.

**Pull request closed without merging**
