### PR TITLE
Allow ServiceBuilder to map requests

### PR DESCRIPTION
**Pull request by carllerche**
Currently, `ServiceBuilder` is not able to include layers that change the request type. This PR demonstrates a potential strategy to fix.

All bounds are removed from the `Layer` trait, essentially reducing it to `Fn(T) -> U` (a trait is needed as one cannot impl `Fn` by hand). Bounds are delayed to the last possible moment.

[Example of maping a request](https://github.com/tower-rs/tower/blob/builder-hax/tower/examples/stack.rs).

### CODE REVIEW

**Comment by carllerche** [comment]
Changing the `stack.rs` example to the following:

```rust
use futures::Future;
use futures::future::lazy;
use tokio;
use tower::{Service, ServiceBuilder};

pub fn main() {
    tokio::run(lazy(|| {
        let my_service = tower::service_fn(|_request: ()| Ok::<_, &'static str>("omg what"));

        let mut service = ServiceBuilder::new()
            .map_request(|request: &'static str| request.to_string())
            .concurrency_limit(100)
            .buffer(5)
            .service(my_service);

        assert!(service.poll_ready().is_ok());

        service.call("hello?")
            .map(|response| {
                println!("resp = {:?}", response);
            })
            .map_err(|_| ())
    }));
}
```

yields this compiler error:

```
error[E0631]: type mismatch in closure arguments
  --> tower/examples/stack.rs:14:14
   |
8  |         let my_service = tower::service_fn(|_request: ()| Ok::<_, &'static str>("omg what"));
   |                                            ------------------------------------------------ found signature of `fn(()) -> _`
...
14 |             .service(my_service);
   |              ^^^^^^^ expected signature of `fn(std::string::String) -> _`
   |
   = note: required because of the requirements on the impl of `tower_service::Service<std::string::String>` for `tower_util::service_fn::ServiceFn<[closure@tower/examples/stack.rs:8:44: 8:92]>`
   = note: required because of the requirements on the impl of `tower_layer::Layer<tower_util::service_fn::ServiceFn<[closure@tower/examples/stack.rs:8:44: 8:92]>>` for `tower_buffer::layer::BufferLayer<std::string::String>`
   = note: required because of the requirements on the impl of `tower_layer::Layer<tower_util::service_fn::ServiceFn<[closure@tower/examples/stack.rs:8:44: 8:92]>>` for `tower_util::layer::stack::Stack<tower_buffer::layer::BufferLayer<std::string::String>, tower_util::layer::stack::Stack<tower_limit::concurrency::layer::ConcurrencyLimitLayer, tower_util::layer::stack::Stack<tower::builder::MapRequest<[closure@tower/examples/stack.rs:11:26: 11:69]>, tower_util::layer::identity::Identity>>>`

error[E0599]: no method named `poll_ready` found for type `tower::builder::MapRequestService<tower_limit::concurrency::service::ConcurrencyLimit<tower_buffer::service::Buffer<tower_util::service_fn::ServiceFn<[closure@tower/examples/stack.rs:8:44: 8:92]>, std::string::String>>, [closure@tower/examples/stack.rs:11:26: 11:69]>` in the current scope
  --> tower/examples/stack.rs:16:25
   |
16 |         assert!(service.poll_ready().is_ok());
   |                         ^^^^^^^^^^
   |
   = note: the method `poll_ready` exists but the following trait bounds were not satisfied:
           `tower::builder::MapRequestService<tower_limit::concurrency::service::ConcurrencyLimit<tower_buffer::service::Buffer<tower_util::service_fn::ServiceFn<[closure@tower/examples/stack.rs:8:44: 8:92]>, std::string::String>>, [closure@tower/examples/stack.rs:11:26: 11:69]> : tower_service::Service<_>`

error[E0599]: no method named `call` found for type `tower::builder::MapRequestService<tower_limit::concurrency::service::ConcurrencyLimit<tower_buffer::service::Buffer<tower_util::service_fn::ServiceFn<[closure@tower/examples/stack.rs:8:44: 8:92]>, std::string::String>>, [closure@tower/examples/stack.rs:11:26: 11:69]>` in the current scope
  --> tower/examples/stack.rs:18:17
   |
18 |         service.call("hello?")
   |                 ^^^^
   |
   = note: the method `call` exists but the following trait bounds were not satisfied:
           `tower::builder::MapRequestService<tower_limit::concurrency::service::ConcurrencyLimit<tower_buffer::service::Buffer<tower_util::service_fn::ServiceFn<[closure@tower/examples/stack.rs:8:44: 8:92]>, std::string::String>>, [closure@tower/examples/stack.rs:11:26: 11:69]> : tower_service::Service<_>`

error: aborting due to 3 previous errors

Some errors occurred: E0599, E0631.
For more information about an error, try `rustc --explain E0599`.
error: Could not compile `tower`.

To learn more, run the command again with --verbose.
```

**Comment by carllerche** [comment]
This error message does not seem so good. I have not yet dug into it (will update)

```rust
use futures::Future;
use futures::future::lazy;
use tokio;
use tower::{Service, ServiceBuilder};
use tower_filter::FilterLayer;

#[derive(Debug)]
struct NotClone;

pub fn main() {
    tokio::run(lazy(|| {
        let not_clone = NotClone;
        let my_service = tower::service_fn(move |_request| {
            Ok::<_, &'static str>(format!("omg what, {:?}", not_clone))
        });

        let mut service = ServiceBuilder::new()
            .map_request(|request: &'static str| request.to_string())
            .concurrency_limit(100)
            // .buffer(5)
            .layer(FilterLayer::new(|_request| Ok(())))
            .service(my_service);

        assert!(service.poll_ready().is_ok());

        service.call("hello?")
            .map(|response| {
                println!("resp = {:?}", response);
            })
            .map_err(|_| ())
    }));
}
```

compiler error:

```
error[E0271]: type mismatch resolving `for<'r> <[closure@tower/examples/stack.rs:21:37: 21:54] as std::ops::FnOnce<(&'r std::string::String,)>>::Output == _`
  --> tower/examples/stack.rs:22:14
   |
22 |             .service(my_service);
   |              ^^^^^^^ expected bound lifetime parameter, found concrete lifetime
   |
   = note: required because of the requirements on the impl of `tower_filter::predicate::Predicate<std::string::String>` for `[closure@tower/examples/stack.rs:21:37: 21:54]`
   = note: required because of the requirements on the impl of `tower_service::Service<std::string::String>` for `tower_filter::Filter<_, [closure@tower/examples/stack.rs:21:37: 21:54]>`
   = note: required because of the requirements on the impl of `tower_service::Service<std::string::String>` for `tower_limit::concurrency::service::ConcurrencyLimit<tower_filter::Filter<_, [closure@tower/examples/stack.rs:21:37: 21:54]>>`
   = note: required because of the requirements on the impl of `tower_service::Service<&'static str>` for `tower::builder::MapRequestService<tower_limit::concurrency::service::ConcurrencyLimit<tower_filter::Filter<_, [closure@tower/examples/stack.rs:21:37: 21:54]>>, [closure@tower/examples/stack.rs:18:26: 18:69]>`

error[E0631]: type mismatch in closure arguments
  --> tower/examples/stack.rs:22:14
   |
21 |             .layer(FilterLayer::new(|_request| Ok(())))
   |                                     ----------------- found signature of `fn(_) -> _`
22 |             .service(my_service);
   |              ^^^^^^^ expected signature of `for<'r> fn(&'r std::string::String) -> _`
   |
   = note: required because of the requirements on the impl of `tower_filter::predicate::Predicate<std::string::String>` for `[closure@tower/examples/stack.rs:21:37: 21:54]`
   = note: required because of the requirements on the impl of `tower_service::Service<std::string::String>` for `tower_filter::Filter<_, [closure@tower/examples/stack.rs:21:37: 21:54]>`
   = note: required because of the requirements on the impl of `tower_service::Service<std::string::String>` for `tower_limit::concurrency::service::ConcurrencyLimit<tower_filter::Filter<_, [closure@tower/examples/stack.rs:21:37: 21:54]>>`
   = note: required because of the requirements on the impl of `tower_service::Service<&'static str>` for `tower::builder::MapRequestService<tower_limit::concurrency::service::ConcurrencyLimit<tower_filter::Filter<_, [closure@tower/examples/stack.rs:21:37: 21:54]>>, [closure@tower/examples/stack.rs:18:26: 18:69]>`

error[E0599]: no method named `poll_ready` found for type `tower::builder::MapRequestService<tower_limit::concurrency::service::ConcurrencyLimit<tower_filter::Filter<tower_util::service_fn::ServiceFn<[closure@tower/examples/stack.rs:13:44: 15:10 not_clone:_]>, [closure@tower/examples/stack.rs:21:37: 21:54]>>, [closure@tower/examples/stack.rs:18:26: 18:69]>` in the current scope
  --> tower/examples/stack.rs:24:25
   |
24 |         assert!(service.poll_ready().is_ok());
   |                         ^^^^^^^^^^
   |
   = note: the method `poll_ready` exists but the following trait bounds were not satisfied:
           `tower::builder::MapRequestService<tower_limit::concurrency::service::ConcurrencyLimit<tower_filter::Filter<tower_util::service_fn::ServiceFn<[closure@tower/examples/stack.rs:13:44: 15:10 not_clone:_]>, [closure@tower/examples/stack.rs:21:37: 21:54]>>, [closure@tower/examples/stack.rs:18:26: 18:69]> : tower_service::Service<_>`

error[E0599]: no method named `call` found for type `tower::builder::MapRequestService<tower_limit::concurrency::service::ConcurrencyLimit<tower_filter::Filter<tower_util::service_fn::ServiceFn<[closure@tower/examples/stack.rs:13:44: 15:10 not_clone:_]>, [closure@tower/examples/stack.rs:21:37: 21:54]>>, [closure@tower/examples/stack.rs:18:26: 18:69]>` in the current scope
  --> tower/examples/stack.rs:26:17
   |
26 |         service.call("hello?")
   |                 ^^^^
   |
   = note: the method `call` exists but the following trait bounds were not satisfied:
           `tower::builder::MapRequestService<tower_limit::concurrency::service::ConcurrencyLimit<tower_filter::Filter<tower_util::service_fn::ServiceFn<[closure@tower/examples/stack.rs:13:44: 15:10 not_clone:_]>, [closure@tower/examples/stack.rs:21:37: 21:54]>>, [closure@tower/examples/stack.rs:18:26: 18:69]> : tower_service::Service<_>`
```

**Comment by carllerche** [comment]
Another case:

```rust
use futures::Future;
use futures::future::lazy;
use tokio;
use tower::{Service, ServiceBuilder};
use tower_filter::FilterLayer;

#[derive(Debug)]
struct NotClone;

pub fn main() {
    tokio::run(lazy(|| {
        let not_clone = NotClone;
        let my_service = tower::service_fn(move |_request| {
            Ok::<_, &'static str>(format!("omg what, {:?}", not_clone))
        });

        let mut service = ServiceBuilder::new()
            .map_request(|request: &'static str| request.to_string())
            .concurrency_limit(100)
            .buffer(5)
            .layer(FilterLayer::new(|_request| Ok(())))
            .service(my_service);

        assert!(service.poll_ready().is_ok());

        service.call("hello?")
            .map(|response| {
                println!("resp = {:?}", response);
            })
            .map_err(|_| ())
    }));
}
```

```
error[E0599]: no method named `service` found for type `tower::builder::ServiceBuilder<tower_util::layer::stack::Stack<tower_filter::layer::FilterLayer<[closure@tower/examples/stack.rs:21:37: 21:54]>, tower_util::layer::stack::Stack<tower_buffer::layer::BufferLayer<_>, tower_util::layer::stack::Stack<tower_limit::concurrency::layer::ConcurrencyLimitLayer, tower_util::layer::stack::Stack<tower::builder::MapRequest<[closure@tower/examples/stack.rs:18:26: 18:69]>, tower_util::layer::identity::Identity>>>>>` in the current scope
  --> tower/examples/stack.rs:22:14
   |
22 |             .service(my_service);
   |              ^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: Could not compile `tower`.
```

**Comment by carllerche** [comment]
The two error messages above are **probably** because i'm passing an invalid closure as a predicate to filter, which adds another level of traits...

When the filter predicate closure is annotated, we a decent error:

```rust
use futures::Future;
use futures::future::lazy;
use tokio;
use tower::{Service, ServiceBuilder};
use tower_filter::FilterLayer;

#[derive(Debug)]
struct NotClone;

pub fn main() {
    tokio::run(lazy(|| {
        let not_clone = NotClone;
        let my_service = tower::service_fn(move |_request| {
            Ok::<_, &'static str>(format!("omg what, {:?}", not_clone))
        });

        let mut service = ServiceBuilder::new()
            .map_request(|request: &'static str| request.to_string())
            .layer(FilterLayer::new(|_request: &String| Ok(())))
            /*
            .concurrency_limit(100)
            .buffer(5)
            */
            .service(my_service);

        assert!(service.poll_ready().is_ok());

        service.call("hello?")
            .map(|response| {
                println!("resp = {:?}", response);
            })
            .map_err(|_| ())
    }));
}
```

error:

```
error[E0277]: the trait bound `NotClone: std::clone::Clone` is not satisfied in `[closure@tower/examples/stack.rs:13:44: 15:10 not_clone:NotClone]`
  --> tower/examples/stack.rs:24:14
   |
24 |             .service(my_service);
   |              ^^^^^^^ within `[closure@tower/examples/stack.rs:13:44: 15:10 not_clone:NotClone]`, the trait `std::clone::Clone` is not implemented for `NotClone`
   |
   = note: required because it appears within the type `[closure@tower/examples/stack.rs:13:44: 15:10 not_clone:NotClone]`
   = note: required because of the requirements on the impl of `std::clone::Clone` for `tower_util::service_fn::ServiceFn<[closure@tower/examples/stack.rs:13:44: 15:10 not_clone:NotClone]>`
   = note: required because of the requirements on the impl of `tower_service::Service<std::string::String>` for `tower_filter::Filter<tower_util::service_fn::ServiceFn<[closure@tower/examples/stack.rs:13:44: 15:10 not_clone:NotClone]>, [closure@tower/examples/stack.rs:19:37: 19:63]>`
   = note: required because of the requirements on the impl of `tower_service::Service<&'static str>` for `tower::builder::MapRequestService<tower_filter::Filter<tower_util::service_fn::ServiceFn<[closure@tower/examples/stack.rs:13:44: 15:10 not_clone:NotClone]>, [closure@tower/examples/stack.rs:19:37: 19:63]>, [closure@tower/examples/stack.rs:18:26: 18:69]>`
```

**Comment by carllerche** [comment]
We also need to evaluate how this impacts compilation time

**Comment by carllerche** [comment]
@seanmonstar the PR looks good to me. However, since I opened it, I cannot +1 it. Feel free to merge it or create a new one that I can +1.

**Comment by drusellers** [comment]
Is `map_request` a soon to be added function? I pulled the latest source and didn't see it but that looks really nice.

**Comment by carllerche** [comment]
@drusellers it was a quick hack to prove a concept. I think something like it would be nice though.

**Comment by drusellers** [comment]
@carllerche ok cool. I can effect that though with a layer, right?

**Comment by carllerche** [comment]
Yep! You could write `MapRequest` outside of the crate. If you want to open an issue to discuss how to bring back mapping combinators into `tower` proper, we can continue discussion there 👍

**Pull request merged**
