### PR TITLE
chore: fix some typos

### PR DESCRIPTION
**Pull request by striezel**
This pull request fixes some typos.

### CODE REVIEW

**Review by GlenDC — APPROVED** [review]
LGTM

**Comment by striezel** [comment]
@GlenDC: It looks like some of the checks do not start despite your approval. Is there anything that can be done to start those checks?

**Comment by GlenDC** [comment]
Hi. It's because I'm not a maintainer. Somebody like @seanmonstar , @davidpdrsn or @hawkw will have to allow the ci to run.

**Comment by tobz** [comment]
Closing in favor of #775, since I couldn't figure out a clean way to fix the merge conflicts on the CLI.

**Pull request closed without merging**
