### PR TITLE
buffer: fix panics if worker executor drops unexpectedly

### PR DESCRIPTION
**Pull request by seanmonstar**

### CODE REVIEW

**Comment by jonhoo** [comment]
This seems to change a bunch of things around, partially related to removing `DirectService` (so we no longer need `method`). What was the actual bug?

**Comment by seanmonstar** [comment]
The tests triggered the panics. They happened if the worker was dropped early without an error. I was seeing it when the Linkerd2 proxy was shutting down, as the runtime dropped.

**Comment by jonhoo** [comment]
I guess what I meant was that it's hard to tease out what exactly the underlying problem was given all the changes. What triggered the panic?

**Comment by seanmonstar** [comment]
The unreachable in future, and the expect in poll_ready.

**Pull request merged**
