### PR TITLE
Upgrade http and sync_wrapper dependencies

### PR DESCRIPTION
**Pull request by elichai**
Upgrade these dependencies to allow downstream users to reduce duplicate dependencies
(specifically this makes `axum` CI fail for duplicate dependencies when upgrading to tower 0.5: https://github.com/tokio-rs/axum/actions/runs/10440315723/job/28910071844?pr=2880 )

### CODE REVIEW

**Comment by tottoto** [comment]
I think this is not breaking change as `http` crate is dev-dependency, and `sync_wrapper`'s type is not exposed and the behaviour is not changed from 0.1.

**Comment by elichai** [comment]
@jplatte Any chance we can get this in 5.1?

**Comment by jplatte** [comment]
Sorry, I maintain `tower-http` but not `tower`. I don't think I even have the right to merge things here.

**Review by jplatte — APPROVED** [review]
I can check though...

**Comment by elichai** [comment]
@seanmonstar ping maybe?

**Comment by kanpov** [comment]
@seanmonstar any update on this? Would be good to eliminate sync_wrapper duplication

**Pull request merged**
