### PR TITLE
Update pin-project to 0.4.0-alpha.11

### PR DESCRIPTION
**Pull request by taiki-e**
There is a breaking change: https://github.com/taiki-e/pin-project/pull/86

### CODE REVIEW

**Comment by LucioFranco** [comment]
@seanmonstar last thing I remember @jonhoo said that -alpha.x will not bump to the next by default. So technically its pinned without `=`?

**Comment by seanmonstar** [comment]
Nope, I just tried in a new directory, settings `futures-core-preview = "0.3.0-alpha.16"`, and it downloaded `alpha.18`.

**Comment by LucioFranco** [comment]
Then sounds like we need to update all the deps in all the tower crates then.

**Pull request merged**
