### PR TITLE
Add feature flag for log support.

### PR DESCRIPTION
**Pull request by samscott89**
Just a quick potential fix to #306 (if desired).

### CODE REVIEW

**Comment by LucioFranco** [comment]
@samscott89 would this still provide tracing support?

**Comment by samscott89** [comment]
I believe so. AFAICT, the idea seems to be move everything to tracing, and then use the `tracing/log` feature to provide compatibility with `log`. (I'm going off of ~ this convo https://github.com/tower-rs/tower/pull/298#discussion_r302291421). Which is on by default since people using log would other see their logs disappear.

The problem is for people using tracing first, and redirecting log outputs to tracing, we now get double the logs. And also a ton of noise since `tracing/log` logs a bunch of extra stuff, like when spans are entered. Although that is a separate thing.

**Comment by hawkw** [comment]
> The problem is for people using tracing first, and redirecting log outputs to tracing, we now get double the logs. And also a ton of noise since tracing/log logs a bunch of extra stuff, like when spans are entered. Although that is a separate thing.

@samscott89 I think there's potentially some strategies we could use to work around the problem of duplicate logs when both `tracing-log`'s `LogTracer` and the log feature flag are in use, though they might need some design --- there's a `tracing` ticket in there for sure.

**Comment by samscott89** [comment]
> > The problem is for people using tracing first, and redirecting log outputs to tracing, we now get double the logs. And also a ton of noise since tracing/log logs a bunch of extra stuff, like when spans are entered. Although that is a separate thing.
> 
> @samscott89 I think there's potentially some strategies we could use to work around the problem of duplicate logs when both `tracing-log`'s `LogTracer` and the log feature flag are in use, though they might need some design --- there's a `tracing` ticket in there for sure.

Hmm, yeah the idea that everyone would expose a `log` feature does seem a bit unwieldy.

I submitted https://github.com/tokio-rs/tracing/issues/204 as a starting point

**Comment by samscott89** [comment]
Okay, I'll close this PR then in favour of solving it in tracing.

**Pull request closed without merging**
