### PR TITLE
util: Fix warning

### PR DESCRIPTION
**Pull request by zhao-gang**
Fixed following warning:

warning: use of deprecated associated function `futures_util::stream::FuturesOrdered::<Fut>::push`: use `push_back` instead
   --> tower/src/util/call_all/ordered.rs:171:25
    |
171 |         FuturesOrdered::push(self, future)
    |                         ^^^^
    |
    = note: `#[warn(deprecated)]` on by default

warning: `tower` (lib) generated 1 warning

### CODE REVIEW

**Review by LucioFranco — APPROVED** [review]
Thanks!

**Comment by LucioFranco** [comment]
Seems to be a snag on ci related to msrv, once that is fixed we can merge.

**Comment by wafuwafu13** [comment]
related https://github.com/tower-rs/tower/pull/735

**Review by tobz — APPROVED** [review]

**Comment by tobz** [comment]
Closing this as it needs a bump to use `futures-util` 0.3.22, and it doesn't seem like I have write permission to update the existing branch.

**Pull request closed without merging**
